version: '3.8'
services:
  portfolio:
    image: sargadi/portfolio
    container_name: portfolio
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - npm

networks:
  npm:
    external: true