name: Build and Push Docker image

on:
  push:
    branches:
      - main # 워크플로우가 트리거될 브랜치

jobs:
  build-and-push:
    runs-on: ubuntu-latest # 실행 환경
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sargadi/portfolio:latest # 수정 필요: Docker Hub 사용자 이름 및 리포지토리 이름

      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /var/snap/docker/portfolio
            ./deploy.sh

      - name: Completion
        run: echo "Deployment completed successfully."
